MYSQL_HOST: ${MYSQL_HOST}
MYSQL_USER: ${MYSQL_USER}
MYSQL_PASSWORD: ${MYSQL_PASSWORD}
MYSQL_DATABASE: ${MYSQL_DATABASE}
MYSQL_TABLE_1: ${MYSQL_TABLE_1}
MYSQL_TABLE_2: ${MYSQL_TABLE_2}
ESRI_API_KEY: ${ESRI_API_KEY}
OUT_DIR: ${OUT_DIR}

